name: iOS build

on:
  [push, workflow_dispatch]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Set up build environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4.0'

      - name: Set up build environment pt. II
        uses: actions/checkout@v2

      - name: Set up build environment pt. III
        run: brew install haxe

      - name: Set Up environment pt. IV
        run: ls
