name: iOS build

on:
  [push, workflow_dispatch]
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - run: |
          lime test ios
